jwt_secret: ENC[AES256_GCM,data:qkwQR1uwUe0L5wm5W20Q5LpZohChciYKuSHtb4xSQ+l68bilLbyh44ehGf0=,iv:r3KiZKprR3PafYAgXc6rr9CW+Iisr2HUyMCM7O/bwZE=,tag:J/y23mjaZj4YQZH8bN/4EQ==,type:str]
azure_tenant_id: ENC[AES256_GCM,data:JMYKDzqpHo9+jcC3wfcByYv1FdyB2VhiGL0HapDQm5TQ65I6,iv:U7K34mR5r6YCiyB0zXMqnRXa0wmnOC16b1q7yfuvc3s=,tag:6jKzInwG8+UcDVenxqu/oQ==,type:str]
azure_client_id: ENC[AES256_GCM,data:XPMRCShoosrbG2XV+F8+4I3VvC1zi4511Q60aJLVkVy+vIXy,iv:VQ/oaX8ruDV+Yf49o9irwvjpREJf8dlRj2rcR731hFw=,tag:IoaMQjOn2Qb22tEtaYKy9g==,type:str]
azure_client_secret: ENC[AES256_GCM,data:xunauUsmAEw9UsyOtLuzxvIbt55TfXcrBeIJ0mgCAd16AdwGuXhk3g==,iv:tdcKncgDVfJt6xM5TqRrUbziVGHvoU2ETthLT98SUzs=,tag:0A/LQuCHaFfn4nxAWXA2SA==,type:str]
sops:
    age:
        - recipient: age1707hs40zh2xwfwsuf08wg906s26wtn65ntrkgjezekgqvpc27frsjxjl7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVXMzMWJ5MSttcFNxaVk1
            d0F5Z2p4MkJGTDBkZFhnbEM5bWwxMWZ1dEFRCk8yaGVsTVRPUElBYnZDVk9jMTUv
            cjRNd21QeHFIZHJhK2tmM0JFbUsyQmsKLS0tIEU5OHRyTE51Y3lRUkFjOEZ5dTIx
            cHlMOHhQVkpPbDVucVYwb3E4U2tIMncK85uk89nNz9gR/bDT1mbXhk64AG4bTlxh
            w5LMVXozh2ERK0k8nIOK78nPfBU2HxnnNo3AUcbm2w2yhK5WNOoa0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T18:21:34Z"
    mac: ENC[AES256_GCM,data:FnpHn71KMRcq9NTwkCY81an7WFcjdR/C23A9TU9jXUVMbtke4+xTGxlbJ+60vP15mCd11Sk4Bd6LHcVlSfZsPBQP/RqPDrKsAasr2W+BR8ipdZHjy8lbGU3eO7d+vSUE5aY5EDqnGqewNzl1fp8BSoj5nkNDh41VwdyxYHBMnxA=,iv:F8wahGmgCRYW3OYHBKmRDXXpbSO9R3K4fFMFyR6vR4U=,tag:fldaagjH8mfSU5LPCzZvBA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
