jwt_secret: ENC[AES256_GCM,data:Y4/wsnBzKXtPOFGg23RPw8lMsu30KgQ5RB88,iv:paeIDhIyglReNQ4j0lNK+FyFStCLjgNTDgcGfowHlMQ=,tag:lP7VnSkL5xbcUVil0i/sZw==,type:str]
resend_api_key: ENC[AES256_GCM,data:YcnJ/L66AQY=,iv:s64PN0CFtQjzugmONWRyzLTfzgdzYWCX1Pjpkd/Gf6k=,tag:fy/TTM4Djr3FUMqDBDQoTA==,type:str]
azure_client_id: ""
azure_tenant_id: ""
azure_client_secret: ""
sops:
    age:
        - recipient: age1707hs40zh2xwfwsuf08wg906s26wtn65ntrkgjezekgqvpc27frsjxjl7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVXMzMWJ5MSttcFNxaVk1
            d0F5Z2p4MkJGTDBkZFhnbEM5bWwxMWZ1dEFRCk8yaGVsTVRPUElBYnZDVk9jMTUv
            cjRNd21QeHFIZHJhK2tmM0JFbUsyQmsKLS0tIEU5OHRyTE51Y3lRUkFjOEZ5dTIx
            cHlMOHhQVkpPbDVucVYwb3E4U2tIMncK85uk89nNz9gR/bDT1mbXhk64AG4bTlxh
            w5LMVXozh2ERK0k8nIOK78nPfBU2HxnnNo3AUcbm2w2yhK5WNOoa0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T21:03:43Z"
    mac: ENC[AES256_GCM,data:c+t9ZJanYDavcki2uJHUGc1CALSFfirgWmXvaoo4LlyRqwP0qFQ3hU3Ia58Z3N90vprIhZQ4N6k3ugsv0wefBQjOSihiwKZqsY+wV2OqXhCymJwXCozoyAvfvbnKabpktMCHQ0Gxdt66K34k0m0j/7qLiI73nJRwsze9OnVCuac=,iv:nancfX6Ha75vIJvoggnKURwjsRSV/Tn/JG5s7VlAvAc=,tag:MJx52CnwuoSgAJGv6p6JMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
