jwt_secret: ENC[AES256_GCM,data:plxkNQXk2qDYJ9sz6GzmPhTC5dWs33XiqRrT+gJ1j4WBPEGn9ZlG1jKAuuM=,iv:m5geSb7wZfX6sg1Oritp/lzGQDO/CdRt8wpaFIsBlFU=,tag:w1WHQNhhm3jc0lYh2nIStA==,type:str]
azure_tenant_id: ENC[AES256_GCM,data:mZDwPbGewdtmg+Pf5FIZtEzud8eYi2+bYJR0g4Qai1d3qnoB,iv:6IklZa8myRy6nKlTXgvUSUKmkWoleYgfYZLPCP4sOeg=,tag:ntEh8J/rXfNMj48hyoO2tA==,type:str]
azure_client_id: ENC[AES256_GCM,data:CJMtqc5a04Lpkb+AVKOUTIZY6+Wkd8btNlrVF7TEnlBQ1GGR,iv:8tdKyrwxSG3AZpSyAuBNQk+wYNrmB7tWBxlrWUCb0h8=,tag:2HpkVtcx5dPVp8eTdE8o5w==,type:str]
azure_client_secret: ENC[AES256_GCM,data:dj9Xwtvwumeg6KaTZk43wC401YnZZEqISXIIDn/mMhTU9oEby/e/eA==,iv:YAfPrQCLqiUN8lXLyMxqZCTrDetL0lSn+6LImBmYlyA=,tag:N7uPFmg5XaaB82oDU/Eo5Q==,type:str]
r2_account_id: ENC[AES256_GCM,data:pcd2k1bpxxBmsT0YW2XTFtFmXsjKybfmxDDpKz8fWvA=,iv:3tdvRFvDDD0HNDFBFa3H9oF7O06NHV3PfE5fjR7WJ+k=,tag:1SAaELrvvnbJ+cB90CQoIw==,type:str]
r2_access_key_id: ENC[AES256_GCM,data:684f19iyx575Ke74/DULPBpQiCZI2mjOjqA8Ej4j6Ok=,iv:C8gRHUfw4Ue79zppUqgcV4m/mKADZxx983UWCMmyvgE=,tag:JBbZ1x/sL5ib+lr7W1iJSg==,type:str]
r2_secret_access_key: ENC[AES256_GCM,data:okDwaBNA+6rkgbW6iABK1nH5cFoGfpnPpHqjSCegK4mGVmcpQ7mzeeSYtwZuTiRy8IV5Ypmk1Fw+g2nnDyeMBQ==,iv:vyO/k0OA3cANYB9A6ahVbfZ8h27WSs9tsMv/s3c6kKo=,tag:yuqnci1Xi4zeeNh7u8Fucw==,type:str]
sops:
    age:
        - recipient: age1707hs40zh2xwfwsuf08wg906s26wtn65ntrkgjezekgqvpc27frsjxjl7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQXFodHVYV2EwenhsL1JW
            aWRXelBlZU03Rm5KNTJPSGNVckJpQ25paFFNCngvRFpFa3c1d2Ixa244VHRtQUlN
            T2RyZE1EVnVTWnJpTkxra3pjVWxFdUUKLS0tIGZMY1FyWGdxNUwrQ3BvLytuSW5P
            c0xnNUJ1QlJ3WW9uOGhwemwweVBlbDAKCVrDqy0sXEfTIQEdDNzp8a//ABRkuVlY
            bmKi/PglulxQucfRtWMOloftZ+1jAHWv43I17ZpYQSWa6KLY9XGedw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T03:02:30Z"
    mac: ENC[AES256_GCM,data:MI6M4UKOzgmnm+pTpUOhhkQcAvTy2gScL5UkpVKxja5lXn88qg2GPf6DcSgil4t8gfrjc2w1Py6UdKQmk0x9acsBUH0pWdOQxbsj2YZcnUXcnpgrDMn3HNCbSLjO+rCOBdVjDnWWYkNhTLCiOTJKz0F/X1wx1QNv/Xnghg4J3Zg=,iv:fgLMTfRP7zsO/DWWR/hKsdEjvtchul8wvVP+RQCf7m8=,tag:bfHSCqmlq74DCVaT9NCwfw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
